### ISSUE TITLE
 TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Pavan-Kolachena** [LazyAGI/LazyLLM#117]
why am getting the above error when am trying to run the code in colab
![unHashable error](https://github.com/user-attachments/assets/377af07f-3ad0-4be6-9b8c-32b367886afa)

**Comment by wzh1994** [comment]
modify `if model in model_name_mapping.keys() and self.model_source in model_name_mapping[model][['source']].keys():` to `if model in model_name_mapping.keys() and self.model_source in model_name_mapping[model]['source'].keys():`

This bug is already solved by https://github.com/LazyAGI/LazyLLM/pull/40 , we will update the v0.2 version within ten days, new software packages and images will be available for you to use
